export const MARKET_SYMBOLS: Record<string, string | string[]> = {
  "United States": "IBM",
  "United Kingdom": "TSCO.LON",
  "Canada": ["SHOP.TRT", "GPV.TRV"],
  "Germany": "MBG.DEX",
  "India": "RELIANCE.BSE",
  "Mainland China": ["600104.SHH", "000002.SHZ"],
  "Australia": "BHP.AX",
  "Japan": "7203.T",
  "Brazil": "PETR4.SA",
  "South Africa": "NPN.JO",
  "Russia": "GAZP.ME",
  "Switzerland": "NESN.SW",
  "South Korea": "005930.KS",
  "Portugal": "EDP.LS",
  "Spain": "SAN.MC",
  "France": "ORA.PA",
  "Hong Kong": "0700.HK",
  "Mexico": "AMXL.MX",
  "Italy": "ENEL.MI",
  "Netherlands": "ASML.AS",
  "Singapore": "D05.SI",
  "Norway": "EQNR.OL",
  "New Zealand": "AIA.NZ",
  "Sweden": "VOLV-B.ST",
  "Denmark": "NOVO-B.CO",
  "Finland": "NOKIA.HE",
  "Belgium": "ABI.BR",
  "Ireland": "CRH.I",
  "Austria": "EBS.VI",
  "Luxembourg": "SESGL.LU",
  "United Arab Emirates": "EMAAR.DU",
  "Qatar": "QNBK.QA",
  "Saudi Arabia": "2222.SR",
  "Turkey": "GARAN.IS",
  "Indonesia": "BBRI.JK",
  "Malaysia": "MAYBANK.KL",
  "Thailand": "PTT.BK",
  "Philippines": "SM.PS",
  "Vietnam": "VIC.HM",
  "Argentina": "GGAL.BA",
  "Chile": "CENCOSUD.SN",
  "Peru": "CREDITC1.LM",
  "Colombia": "EC.CN",
  "Egypt": "HRHO.CA",
  "Israel": "TEVA.TA",
  "Pakistan": "HUBC.KA",
  "Forex": "EURUSD",
  "Cryptocurrency": ["BTCUSD", "ETHUSD", "LTCUSD", "XRPUSD"],
  "Global": ["EURUSD", "BTCUSD", "ETHUSD", "LTCUSD", "XRPUSD"]
};